In [48]:
import pandas as pd
import unicodedata
import re

In [2]:
df = pd.read_csv('vendas_modificado.csv')

In [3]:
df.head(20)

,id_da_compra,data,hora,cliente,produto,valor,quantidade,total,status,cidade,estado,pais,cep,frete,pagamento,vendedor,marca
0,13679,2021-03-20,23:35:51,LUCAS Araujo Kuhn,Queijo Mussarela,"R$ 16,87",13,239.31,Pagamento Confirmado,Niterói,RJ,Brasil,24000-000,20.0,Cartão de Crédito,SAMUEL HENRIQUE CAÇADOR,Porto Alegre
1,28070,2020-10-30,09:00:53,MICAEL SOUZA RONCETE,Molho de Tomate,"R$ 3,25",3,9.75,Pagamento Confirmado,Mariana,MG,Brasil,35420-000,0.0,Pix,MICAEL MALAQUIAS DE SOUZA OLIVEIRA,Fugini
2,47484,2021-06-09,15:30:28,FELIPE AUGUSTO NERY SILVA,Água Mineral,"R$ 1,63",9,36.67,Pagamento Confirmado,Cabo Frio,RJ,Brasil,28900-000,22.0,Transferência Bancária,HENRICO MATOS LIMA DA CUNHA,Minalba
3,20809,2022-06-04,08:41:23,LEVI RIBEIRO AMORIM,Carvão,"R$ 8,74",4,54.96,Em Separação,Campos dos Goytacazes,RJ,Brasil,28000-000,20.0,Pix,GABRIEL QUEIROZ DE AGUIAR,Marca-Brás
4,47123,2019-05-04,13:38:45,GABRIEL MATOS LIMA DA CUNHA,Café,"R$ 9,48",2,18.96,Em Separação,Conselheiro Lafaiete,MG,Brasil,36400-000,0.0,Cartão de Crédito,HENRICO MATOS LIMA DA CUNHA,3 Corações
5,38623,2018-02-19,17:32:01,LUCAS ANTÔNIO DE SOUZA NETO,Café,"R$ 10,16",1,20.16,Entregue com Sucesso,Resende Costa,MG,Brasil,36340-000,10.0,Transferência Bancária,VICTOR GONÇALVES DONADONI,3 Corações
6,46627,2018-04-21,22:08:30,GUILHERME IVAIR DE ASSIS SETTA,Feijão,"R$ 7,77",3,43.31,Em Separação,São Paulo,SP,Brasil,01000-000,20.0,Pix,SAMUEL HENRIQUE CAÇADOR,Caldo Bom
7,53579,2020-09-25,12:04:15,GABRIEL MUZY FERNANDES,Queijo Mussarela,"R$ 14,93",14,218.02,Em Separação,Bicas,MG,Brasil,36600-000,9.0,Boleto,MICAEL MALAQUIAS DE SOUZA OLIVEIRA,Porto Alegre
8,34924,2018-06-20,17:10:42,LEVI MATOS LIMA DA CUNHA,Condicionador,"R$ 9,51",5,69.55,Pagamento Confirmado,Cabo Frio,RJ,Brasil,28900-000,22.0,Pix,FELIPE HENRIQUE COSTA BARNABE MARAZO,Pantene
9,10575,2018-10-01,18:36:45,HENRICO DA CUNHA TEIXEIRA,Sabonete,"R$ 1,25",2,13.00,Em Separação,São João del-Rei,MG,Brasil,36300-000,10.5,Boleto,GABRIEL QUEIROZ DE AGUIAR,Dove
10,43813,2021-06-04,21:07:04,PEDRO MATOS LIMA DA CUNHA,Açúcar,"R$ 3,59",1,3.59,Aguardando Pagamento,São Gonçalo,RJ,Brasil,24400-000,0.0,Transferência Bancária,SAMUEL HENRIQUE CAÇADOR,Caravelas
11,7597,2021-09-15,07:46:58,MATEUS LACERDA PORTUGAL DA SILVA,Água Mineral,"R$ 1,63",13,39.19,Aguardando Pagamento,São Bernardo do Campo,SP,Brasil,09700-000,18.0,Cartão de Crédito,HENRICO VICTOR ALVES,Crystal
12,10784,2020-07-03,22:34:21,MATEUS VICTOR ALVES,Manteiga,"R$ 6,61",8,71.88,Em Transporte,Duque de Caxias,RJ,Brasil,25000-000,19.0,Pix à Vista,SAMUEL HENRIQUE CAÇADOR,Itambé
13,1271,2021-04-18,10:56:01,CARLOS ASSIS NOGUEIRA SILVA,Papel Higiênico,"R$ 3,89",12,46.68,Em Separação,Macaé,RJ,Brasil,27900-000,0.0,Transferência Bancária,MICAEL MALAQUIAS DE SOUZA OLIVEIRA,Neve
14,41008,2021-04-25,15:20:19,VICTOR SANTOS DA SILVA,Óleo de Soja,"R$ 3,22",12,58.64,Pagamento Confirmado,São Paulo,SP,Brasil,01000-000,20.0,Cartão de Crédito,HENRICO MATOS LIMA DA CUNHA,Liza
15,5650,2021-06-11,14:18:25,VICTOR DA CUNHA TEIXEIRA,Café,"R$ 5,29",1,5.29,Em Separação,Viçosa,MG,Brasil,36570-000,0.0,Transferência Bancária,MICAEL MALAQUIAS DE SOUZA OLIVEIRA,3 Corações
16,22499,2021-05-10,16:03:02,HENRIQUE PICANÇO SANTOS FERREIRA SILVA,Café,"R$ 9,35",2,18.70,Em Separação,Resende Costa,MG,Brasil,36340-000,0.0,Pix,GABRIEL QUEIROZ DE AGUIAR,3 Corações
17,24847,2022-06-23,12:15:47,THIAGO LACERDA PORTUGAL DA SILVA,Açúcar,"R$ 3,75",3,24.25,Em Separação,Juiz de Fora,MG,Brasil,36000-000,13.0,Transferência Bancária,SAMUEL HENRIQUE CAÇADOR,Caravelas
18,12051,2020-07-23,15:37:50,ARTHUR FELIPE DE SOUZA,Café,"R$ 9,45",3,28.35,AP,Guarulhos,SP,Brasil,07000-000,0.0,Boleto,HENRICO VICTOR ALVES,3 Corações
19,51716,2021-03-13,09:10:41,MIGUEL MURATORI DUTRA,Molho de Tomate,"R$ 3,31",2,6.62,Em Separação,Matias Barbosa,MG,Brasil,36120-000,0.0,Cartão de Crédito,CARLOS QUEIROZ DE AGUIAR,Predilecta

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 368752 entries, 0 to 368751
Data columns (total 17 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   id_da_compra  368752 non-null  int64
 1   data          368752 non-null  object
 2   hora          368752 non-null  object
 3   cliente       368752 non-null  object
 4   produto       368752 non-null  object
 5   valor         368752 non-null  object
 6   quantidade    368752 non-null  int64
 7   total         365067 non-null  float64
 8   status        368752 non-null  object
 9   cidade        368752 non-null  object
 10  estado        368752 non-null  object
 11  pais          368752 non-null  object
 12  cep           368752 non-null  object
 13  frete         361381 non-null  float64
 14  pagamento     368752 non-null  object
 15  vendedor      365072 non-null  object
 16  marca         368752 non-null  object
dtypes: float64(2), int64(2), object(13)
memory usage: 47.8+ MB

In [7]:
df.isnull().sum()

id_da_compra       0
data               0
hora               0
cliente            0
produto            0
valor              0
quantidade         0
total           3685
status             0
cidade             0
estado             0
pais               0
cep                0
frete           7371
pagamento          0
vendedor        3680
marca              0
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(5158)

In [9]:
colunas_numericas = ['valor', 'quantidade', 'total', 'frete']

for coluna in colunas_numericas:
    df[coluna] = df[coluna].astype(str).str.replace(',', '.', regex=False)

In [10]:
for coluna in colunas_numericas:
    df[coluna] = pd.to_numeric(df[coluna], errors='coerce')

In [11]:
df[colunas_numericas].dtypes

valor         float64
quantidade      int64
total         float64
frete         float64
dtype: object

In [12]:
df.isnull().sum()

id_da_compra         0
data                 0
hora                 0
cliente              0
produto              0
valor           368752
quantidade           0
total             3685
status               0
cidade               0
estado               0
pais                 0
cep                  0
frete             7371
pagamento            0
vendedor          3680
marca                0
dtype: int64

In [13]:
df['valor'] = df['valor'].fillna(0)
df['quantidade'] = df['quantidade'].fillna(df['quantidade'].median())
df['total'] = df['total'].fillna(df['total'].median())
df['frete'] = df['frete'].fillna(df['frete'].median())

In [14]:
df['data'] = pd.to_datetime(df['data'], errors='coerce')

In [15]:
df['hora'] = pd.to_datetime(df['hora'], errors='coerce').dt.time

C:\Users\Breno\AppData\Local\Temp\ipykernel_6972\3899559563.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['hora'] = pd.to_datetime(df['hora'], errors='coerce').dt.time

In [16]:
df['hora_ideal'] = df['hora'].apply(lambda x: x.strftime('%H%M%S') if pd.notnull(x) else None)

In [17]:
df[['hora', 'hora_ideal']].head()

       hora hora_ideal
0  23:35:51     233551
1  09:00:53     090053
2  15:30:28     153028
3  08:41:23     084123
4  13:38:45     133845

In [18]:
df['hora_ideal'].dtype

dtype('O')

In [19]:
df['hora_ideal'].isnull().sum()

np.int64(0)

In [20]:
df['vendedor'] = df['vendedor'].fillna('Desconhecido')

In [21]:
df = df.drop_duplicates()

In [22]:
df.isnull().sum()

id_da_compra    0
data            0
hora            0
cliente         0
produto         0
valor           0
quantidade      0
total           0
status          0
cidade          0
estado          0
pais            0
cep             0
frete           0
pagamento       0
vendedor        0
marca           0
hora_ideal      0
dtype: int64

In [23]:
df.duplicated().sum()

np.int64(0)

In [24]:
df = df.drop_duplicates()

In [25]:
df = df.drop_duplicates(subset=['id_da_compra'])

In [26]:
df.duplicated().sum()

np.int64(0)

In [27]:
df['total_calculado'] = (df['valor'] * df['quantidade']) + df['frete']

In [28]:
df['total_corretamente_calculado'] = df['total'] == df['total_calculado']

In [29]:
df[df['total_corretamente_calculado'] == False]

,id_da_compra,data,hora,cliente,produto,valor,quantidade,total,status,cidade,estado,pais,cep,frete,pagamento,vendedor,marca,hora_ideal,total_calculado,total_corretamente_calculado
0,13679,2021-03-20,23:35:51,LUCAS Araujo Kuhn,Queijo Mussarela,0.0,13,239.31,Pagamento Confirmado,Niterói,RJ,Brasil,24000-000,20.0,Cartão de Crédito,SAMUEL HENRIQUE CAÇADOR,Porto Alegre,233551,20.0,False
1,28070,2020-10-30,09:00:53,MICAEL SOUZA RONCETE,Molho de Tomate,0.0,3,9.75,Pagamento Confirmado,Mariana,MG,Brasil,35420-000,0.0,Pix,MICAEL MALAQUIAS DE SOUZA OLIVEIRA,Fugini,090053,0.0,False
2,47484,2021-06-09,15:30:28,FELIPE AUGUSTO NERY SILVA,Água Mineral,0.0,9,36.67,Pagamento Confirmado,Cabo Frio,RJ,Brasil,28900-000,22.0,Transferência Bancária,HENRICO MATOS LIMA DA CUNHA,Minalba,153028,22.0,False
3,20809,2022-06-04,08:41:23,LEVI RIBEIRO AMORIM,Carvão,0.0,4,54.96,Em Separação,Campos dos Goytacazes,RJ,Brasil,28000-000,20.0,Pix,GABRIEL QUEIROZ DE AGUIAR,Marca-Brás,084123,20.0,False
4,47123,2019-05-04,13:38:45,GABRIEL MATOS LIMA DA CUNHA,Café,0.0,2,18.96,Em Separação,Conselheiro Lafaiete,MG,Brasil,36400-000,0.0,Cartão de Crédito,HENRICO MATOS LIMA DA CUNHA,3 Corações,133845,0.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
349263,2257,2021-10-01,08:43:16,PAULO QUEIROZ DE AGUIAR,Sal,0.0,14,25.62,Pagamento Confirmado,Santo André,SP,Brasil,09000-000,0.0,Transferência Bancária,MICAEL MALAQUIAS DE SOUZA OLIVEIRA,Lebre,084316,0.0,False
351464,184,2018-11-23,14:29:40,GABRIEL CARLOS DE SOUZA,Pasta de Dente,0.0,3,7.71,Pagamento Confirmado,Volta Redonda,RJ,Brasil,27200-000,0.0,Pix,VICTOR GONÇALVES DONADONI,Sorriso,142940,0.0,False
354008,34046,2018-10-01,17:54:41,RÔMULO SILVA RAMOS,Shampoo,0.0,8,91.52,Pagamento Confirmado,São Paulo,SP,Brasil,01000-000,20.0,Boleto,PAULO SOUZA RONCETE,Dove,175441,20.0,False
355405,8015,2019-09-05,02:08:50,JOÃO CARLOS DE SOUZA,Café#$@!,0.0,4,38.40,Pagamento Confirmado,Duque de Caxias,RJ,Brasil,25000-000,0.0,Pix,CARLOS QUEIROZ DE AGUIAR,3 Corações,020850,0.0,False
358959,51039,2020-05-31,08:18:03,Breno RIBAS DE MOURA,Sal,0.0,8,34.82,Aguardando Pagamento,Ouro Preto,MG,Brasil,35400-000,-12.5,Cartão de Crédito,SAMUEL HENRIQUE CAÇADOR,Marinho,081803,-12.5,False

In [30]:
df.head(5)

,id_da_compra,data,hora,cliente,produto,valor,quantidade,total,status,cidade,estado,pais,cep,frete,pagamento,vendedor,marca,hora_ideal,total_calculado,total_corretamente_calculado
0,13679,2021-03-20,23:35:51,LUCAS Araujo Kuhn,Queijo Mussarela,0.0,13,239.31,Pagamento Confirmado,Niterói,RJ,Brasil,24000-000,20.0,Cartão de Crédito,SAMUEL HENRIQUE CAÇADOR,Porto Alegre,233551,20.0,False
1,28070,2020-10-30,09:00:53,MICAEL SOUZA RONCETE,Molho de Tomate,0.0,3,9.75,Pagamento Confirmado,Mariana,MG,Brasil,35420-000,0.0,Pix,MICAEL MALAQUIAS DE SOUZA OLIVEIRA,Fugini,090053,0.0,False
2,47484,2021-06-09,15:30:28,FELIPE AUGUSTO NERY SILVA,Água Mineral,0.0,9,36.67,Pagamento Confirmado,Cabo Frio,RJ,Brasil,28900-000,22.0,Transferência Bancária,HENRICO MATOS LIMA DA CUNHA,Minalba,153028,22.0,False
3,20809,2022-06-04,08:41:23,LEVI RIBEIRO AMORIM,Carvão,0.0,4,54.96,Em Separação,Campos dos Goytacazes,RJ,Brasil,28000-000,20.0,Pix,GABRIEL QUEIROZ DE AGUIAR,Marca-Brás,084123,20.0,False
4,47123,2019-05-04,13:38:45,GABRIEL MATOS LIMA DA CUNHA,Café,0.0,2,18.96,Em Separação,Conselheiro Lafaiete,MG,Brasil,36400-000,0.0,Cartão de Crédito,HENRICO MATOS LIMA DA CUNHA,3 Corações,133845,0.0,False

In [31]:
df.tail()

,id_da_compra,data,hora,cliente,produto,valor,quantidade,total,status,cidade,estado,pais,cep,frete,pagamento,vendedor,marca,hora_ideal,total_calculado,total_corretamente_calculado
349263,2257,2021-10-01,08:43:16,PAULO QUEIROZ DE AGUIAR,Sal,0.0,14,25.62,Pagamento Confirmado,Santo André,SP,Brasil,09000-000,0.0,Transferência Bancária,MICAEL MALAQUIAS DE SOUZA OLIVEIRA,Lebre,084316,0.0,False
351464,184,2018-11-23,14:29:40,GABRIEL CARLOS DE SOUZA,Pasta de Dente,0.0,3,7.71,Pagamento Confirmado,Volta Redonda,RJ,Brasil,27200-000,0.0,Pix,VICTOR GONÇALVES DONADONI,Sorriso,142940,0.0,False
354008,34046,2018-10-01,17:54:41,RÔMULO SILVA RAMOS,Shampoo,0.0,8,91.52,Pagamento Confirmado,São Paulo,SP,Brasil,01000-000,20.0,Boleto,PAULO SOUZA RONCETE,Dove,175441,20.0,False
355405,8015,2019-09-05,02:08:50,JOÃO CARLOS DE SOUZA,Café#$@!,0.0,4,38.40,Pagamento Confirmado,Duque de Caxias,RJ,Brasil,25000-000,0.0,Pix,CARLOS QUEIROZ DE AGUIAR,3 Corações,020850,0.0,False
358959,51039,2020-05-31,08:18:03,Breno RIBAS DE MOURA,Sal,0.0,8,34.82,Aguardando Pagamento,Ouro Preto,MG,Brasil,35400-000,-12.5,Cartão de Crédito,SAMUEL HENRIQUE CAÇADOR,Marinho,081803,-12.5,False

In [34]:
df[df['quantidade'] < 0]

Empty DataFrame
Columns: [id_da_compra, data, hora, cliente, produto, valor, quantidade, total, status, cidade, estado, pais, cep, frete, pagamento, vendedor, marca, hora_ideal, total_calculado, total_corretamente_calculado]
Index: []

In [35]:
df[(df['valor'] < 0) | (df['valor'] > 10000)]

Empty DataFrame
Columns: [id_da_compra, data, hora, cliente, produto, valor, quantidade, total, status, cidade, estado, pais, cep, frete, pagamento, vendedor, marca, hora_ideal, total_calculado, total_corretamente_calculado]
Index: []

In [36]:
df['total_calculado'] = (df['valor'] * df['quantidade']) + df['frete']

In [37]:
df['total_corretamente_calculado'] = df['total'] == df['total_calculado']

In [38]:
df[df['total_corretamente_calculado'] == False]

,id_da_compra,data,hora,cliente,produto,valor,quantidade,total,status,cidade,estado,pais,cep,frete,pagamento,vendedor,marca,hora_ideal,total_calculado,total_corretamente_calculado
0,13679,2021-03-20,23:35:51,LUCAS Araujo Kuhn,Queijo Mussarela,0.0,13,239.31,Pagamento Confirmado,Niterói,RJ,Brasil,24000-000,20.0,Cartão de Crédito,SAMUEL HENRIQUE CAÇADOR,Porto Alegre,233551,20.0,False
1,28070,2020-10-30,09:00:53,MICAEL SOUZA RONCETE,Molho de Tomate,0.0,3,9.75,Pagamento Confirmado,Mariana,MG,Brasil,35420-000,0.0,Pix,MICAEL MALAQUIAS DE SOUZA OLIVEIRA,Fugini,090053,0.0,False
2,47484,2021-06-09,15:30:28,FELIPE AUGUSTO NERY SILVA,Água Mineral,0.0,9,36.67,Pagamento Confirmado,Cabo Frio,RJ,Brasil,28900-000,22.0,Transferência Bancária,HENRICO MATOS LIMA DA CUNHA,Minalba,153028,22.0,False
3,20809,2022-06-04,08:41:23,LEVI RIBEIRO AMORIM,Carvão,0.0,4,54.96,Em Separação,Campos dos Goytacazes,RJ,Brasil,28000-000,20.0,Pix,GABRIEL QUEIROZ DE AGUIAR,Marca-Brás,084123,20.0,False
4,47123,2019-05-04,13:38:45,GABRIEL MATOS LIMA DA CUNHA,Café,0.0,2,18.96,Em Separação,Conselheiro Lafaiete,MG,Brasil,36400-000,0.0,Cartão de Crédito,HENRICO MATOS LIMA DA CUNHA,3 Corações,133845,0.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
349263,2257,2021-10-01,08:43:16,PAULO QUEIROZ DE AGUIAR,Sal,0.0,14,25.62,Pagamento Confirmado,Santo André,SP,Brasil,09000-000,0.0,Transferência Bancária,MICAEL MALAQUIAS DE SOUZA OLIVEIRA,Lebre,084316,0.0,False
351464,184,2018-11-23,14:29:40,GABRIEL CARLOS DE SOUZA,Pasta de Dente,0.0,3,7.71,Pagamento Confirmado,Volta Redonda,RJ,Brasil,27200-000,0.0,Pix,VICTOR GONÇALVES DONADONI,Sorriso,142940,0.0,False
354008,34046,2018-10-01,17:54:41,RÔMULO SILVA RAMOS,Shampoo,0.0,8,91.52,Pagamento Confirmado,São Paulo,SP,Brasil,01000-000,20.0,Boleto,PAULO SOUZA RONCETE,Dove,175441,20.0,False
355405,8015,2019-09-05,02:08:50,JOÃO CARLOS DE SOUZA,Café#$@!,0.0,4,38.40,Pagamento Confirmado,Duque de Caxias,RJ,Brasil,25000-000,0.0,Pix,CARLOS QUEIROZ DE AGUIAR,3 Corações,020850,0.0,False
358959,51039,2020-05-31,08:18:03,Breno RIBAS DE MOURA,Sal,0.0,8,34.82,Aguardando Pagamento,Ouro Preto,MG,Brasil,35400-000,-12.5,Cartão de Crédito,SAMUEL HENRIQUE CAÇADOR,Marinho,081803,-12.5,False

In [39]:
colunas_texto = ['cliente', 'produto', 'status', 'cidade', 'estado', 'pais', 'pagamento', 'vendedor', 'marca']
df[colunas_texto] = df[colunas_texto].fillna('Não informado')

In [40]:
colunas_numericas = ['valor', 'quantidade', 'total', 'frete', 'total_calculado']
df[colunas_numericas] = df[colunas_numericas].fillna(0)

In [41]:
for col in ['status', 'pagamento', 'pais']:
    print(f"\nColuna: {col}")
    print(df[col].unique())

Coluna: status
['Pagamento Confirmado' 'Em Separação' 'Entregue com Sucesso'
 'Aguardando Pagamento' 'Em Transporte' 'AP' 'Entregue' 'PC' 'Sep'
 'Separando' 'Pgto Confirmado' 'Transp' 'Transportando' 'Entg'
 'aguardando pagamento' 'Aguardando Pgto']

Coluna: pagamento
['Cartão de Crédito' 'Pix' 'Transferência Bancária' 'Boleto' 'Pix à Vista'
 'Cartão Crédito à Vista' 'Pagamento Instantâneo' 'Cartão Crédito'
 'Boleto à Vista' 'DOC' 'TED' 'Boleto no Dinheiro']

Coluna: pais
['Brasil']

In [42]:
df['status'] = df['status'].str.lower().str.capitalize()
df['pagamento'] = df['pagamento'].str.lower().str.capitalize()
df['pais'] = df['pais'].str.upper()

In [44]:
def normalizar_texto(texto):
    if pd.isnull(texto):
        return texto
    texto = str(texto).lower()
    texto = unicodedata.normalize('NFKD', texto).encode('ASCII', 'ignore').decode('utf-8')
    return texto.strip()

In [46]:
df['produto'] = df['produto'].apply(normalizar_texto)
df['marca'] = df['marca'].apply(normalizar_texto)

In [49]:
def normalizar_produto(texto):
    if pd.isnull(texto):
        return texto
    texto = str(texto).lower()
    texto = unicodedata.normalize('NFKD', texto).encode('ASCII', 'ignore').decode('utf-8')
    texto = re.sub(r'[^a-z0-9\s]', '', texto)
    return texto.strip()

In [50]:
df['produto'] = df['produto'].apply(normalizar_produto)

In [51]:
print(df['produto'].unique())

['queijo mussarela' 'molho de tomate' 'agua mineral' 'carvao' 'cafe'
 'feijao' 'condicionador' 'sabonete' 'acucar' 'manteiga' 'papel higienico'
 'oleo de soja' 'vinho' 'macarrao' 'shampoo' 'presunto' 'cerveja'
 'papel toalha' 'pasta de dente' 'pao de forma' 'sabao em po' 'amaciante'
 'desinfetante' 'refrigerante' 'arroz' 'farinha de trigo'
 'biscoito recheado' 'sal' 'suco de laranja' 'leite integral' 'detergente'
 'refrigkrante' 'scl' 'agua mineras' 'presuntd']

In [52]:
correcoes = {
    'refrigkrante': 'refrigerante',
    'scl': 'sal',
    'agua mineras': 'agua mineral',
    'presuntd': 'presunto'
}

df['produto'] = df['produto'].replace(correcoes)

In [53]:
def normalizar_marca(texto):
    if pd.isnull(texto):
        return texto
    texto = str(texto).lower()
    texto = unicodedata.normalize('NFKD', texto).encode('ASCII', 'ignore').decode('utf-8')
    texto = texto.replace('-', ' ')
    texto = re.sub(r'[^a-z0-9\s]', '', texto)
    return texto.strip()

df['marca'] = df['marca'].apply(normalizar_marca)

In [54]:
correcoes_marca = {
    'guarana antartica': 'guarana antarctica',
    'ki brasa': 'kibrasa'
}

df['marca'] = df['marca'].replace(correcoes_marca)

In [55]:
df['cep'] = df['cep'].astype(str).str.replace('-', '').str.strip()

In [56]:
df['cep_valido'] = df['cep'].str.match(r'^\d{8}$')

In [57]:
ceps_invalidos = df[~df['cep_valido']]
print(ceps_invalidos[['cep']])

             cep
59      361X8XXX
61      366XXXXX
162     3677XXXX
173     36325XXX
180     36345XXX
...          ...
270547  3671XXXX
293594  13XXXXXX
299008  272XXXXX
299118  365XXXXX
315052  28XXXXXX

[1182 rows x 1 columns]

In [58]:
def validar_cep(cep):
    if pd.isnull(cep):
        return False
    cep = str(cep).strip()
    return bool(re.match(r'^\d{5}-?\d{3}$', cep))

In [59]:
df['cep_valido'] = df['cep'].apply(validar_cep)

In [60]:
df = df[df['cep_valido']]

In [61]:
for col in df.select_dtypes(include='object').columns:
    amostras = df[col].sample(3).tolist()
    print(f"{col}: {amostras}")

hora: [datetime.time(14, 25, 23), datetime.time(9, 57, 24), datetime.time(9, 38, 24)]
cliente: ['JOÃO DA SILVA BIANQUINI', 'MARCO DA SILVA BIANQUINI', 'MIGUEL WILSTONY DE SOUZA MENDES']
produto: ['condicionador', 'suco de laranja', 'manteiga']
status: ['Em transporte', 'Pagamento confirmado', 'Em transporte']
cidade: ['Leopoldina', 'Itaboraí', 'Duque de Caxias']
estado: ['RJ', 'RJ', 'MG']
pais: ['BRASIL', 'BRASIL', 'BRASIL']
cep: ['36510000', '25500000', '36680000']
pagamento: ['Cartão de crédito', 'Transferência bancária', 'Cartão de crédito']
vendedor: ['HENRICO MATOS LIMA DA CUNHA', 'LUCAS VITOR FAÇANHA NEVES', 'MICAEL MALAQUIAS DE SOUZA OLIVEIRA']
marca: ['adria', 'uniao', '3 coracoes']
hora_ideal: ['092829', '143550', '190022']

In [62]:
for col in ['status', 'pagamento', 'pais']:
    print(f"\n{col}: {df[col].unique()}")

status: ['Pagamento confirmado' 'Em separação' 'Entregue com sucesso'
 'Aguardando pagamento' 'Em transporte' 'Ap' 'Entregue' 'Pc' 'Sep'
 'Separando' 'Pgto confirmado' 'Transp' 'Transportando' 'Entg'
 'Aguardando pgto']

pagamento: ['Cartão de crédito' 'Pix' 'Transferência bancária' 'Boleto' 'Pix à vista'
 'Cartão crédito à vista' 'Pagamento instantâneo' 'Cartão crédito'
 'Boleto à vista' 'Doc' 'Ted' 'Boleto no dinheiro']

pais: ['BRASIL']

In [63]:
correcoes_status = {
    'Pgto confirmado': 'Pagamento confirmado',
    'Aguardando pgto': 'Aguardando pagamento',
    'Em separação': 'Separando',
    'Sep': 'Separando',
    'Ap': 'Aguardando pagamento',
    'Pc': 'Pagamento confirmado',
    'Transp': 'Em transporte',
    'Entg': 'Entregue',
    'Transportando': 'Em transporte',
    'Entregue com sucesso': 'Entregue'
}

correcoes_pagamento = {
    'Cartão crédito': 'Cartão de crédito',
    'Cartão crédito à vista': 'Cartão de crédito',
    'Pix à vista': 'Pix',
    'Boleto à vista': 'Boleto',
    'Doc': 'Transferência bancária',
    'Ted': 'Transferência bancária',
    'Boleto no dinheiro': 'Boleto'
}

df['status'] = df['status'].replace(correcoes_status)
df['pagamento'] = df['pagamento'].replace(correcoes_pagamento)

In [64]:
df['valor'] = df['total'] / df['quantidade']

In [66]:
print(df[['produto', 'total', 'quantidade', 'valor']].head(5))

            produto   total  quantidade      valor
0  queijo mussarela  239.31          13  18.408462
1   molho de tomate    9.75           3   3.250000
2      agua mineral   36.67           9   4.074444
3            carvao   54.96           4  13.740000
4              cafe   18.96           2   9.480000

In [67]:
df['total_calculado'] = df['total'] + df['frete']

In [68]:
medianas = df.groupby('produto')['valor'].median()

In [69]:
df['valor'] = df['produto'].map(medianas)

In [70]:
df['total'] = df['valor'] * df['quantidade']

In [71]:
df['total_calculado'] = df['total'] + df['frete']

In [72]:
df['estado'] = df['estado'].replace({
    'São Paulo': 'SP',
    'MTSa': 'MT',
    'PSC': 'SC'})

In [73]:
df['produto'] = df['produto'].str.lower().str.strip()

In [74]:
print(df['produto'].value_counts())

produto
pasta de dente       3975
queijo mussarela     3898
manteiga             3813
sabonete             3694
acucar               3517
cafe                 3414
papel toalha         2984
desinfetante         2816
molho de tomate      2078
condicionador        1892
presunto             1635
vinho                1623
agua mineral         1619
detergente           1619
macarrao             1614
biscoito recheado    1601
shampoo              1563
sal                  1552
refrigerante         1531
farinha de trigo     1525
oleo de soja         1519
suco de laranja      1458
cerveja              1361
pao de forma         1125
arroz                1049
feijao               1046
papel higienico       910
amaciante             814
leite integral        810
sabao em po           538
carvao                225
Name: count, dtype: int64

In [75]:
mediana_frete = df[df['frete'] >= 0]['frete'].median()
df['frete'] = df['frete'].apply(lambda x: mediana_frete if x < 0 else x)

In [76]:
limite_superior = df['frete'].quantile(0.99)

df['frete'] = df['frete'].apply(lambda x: limite_superior if x > limite_superior else x)

In [77]:
df['marca'] = df['marca'].str.lower().str.strip()

In [78]:
df['total_calculado'] = df['total'] + df['frete']

In [79]:
df['frete'] = df['frete'].apply(lambda x: 0 if x < 0 else x)

limite_superior = df['frete'].quantile(0.99)
df['frete'] = df['frete'].apply(lambda x: limite_superior if x > limite_superior else x)

df['total_calculado'] = df['total'] + df['frete']

In [80]:
(df['cliente'].str.startswith(' ') | df['cliente'].str.endswith(' ')).sum()

np.int64(1770)

In [81]:
for col in df.columns:
    print(f"{col}: {(df[col] == '').sum()} valores vazios")

id_da_compra: 0 valores vazios
data: 0 valores vazios
hora: 0 valores vazios
cliente: 0 valores vazios
produto: 0 valores vazios
valor: 0 valores vazios
quantidade: 0 valores vazios
total: 0 valores vazios
status: 0 valores vazios
cidade: 0 valores vazios
estado: 0 valores vazios
pais: 0 valores vazios
cep: 0 valores vazios
frete: 0 valores vazios
pagamento: 0 valores vazios
vendedor: 0 valores vazios
marca: 0 valores vazios
hora_ideal: 0 valores vazios
total_calculado: 0 valores vazios
total_corretamente_calculado: 0 valores vazios
cep_valido: 0 valores vazios

In [82]:
df['produto'] = df['produto'].str.title()

In [83]:
df['produto'] = df['produto'].str.strip().str.lower()

In [84]:
df['produto'] = df['produto'].str.strip()
df['produto'] = df['produto'].str.lower()

In [85]:
produtos_baixa_freq = df['produto'].value_counts()[df['produto'].value_counts() < 100]
print(produtos_baixa_freq)

Series([], Name: count, dtype: int64)

In [86]:
df = df.drop_duplicates(subset='produto')

In [87]:
pd.set_option('display.max_rows', None)
df[['produto', 'valor']]

              produto      valor
0    queijo mussarela  15.910000
1     molho de tomate   4.581667
2        agua mineral   2.626667
3              carvao   8.764615
4                cafe  11.870000
6              feijao   9.395000
8       condicionador  10.870000
9            sabonete   2.646667
10             acucar   3.985000
12           manteiga   8.750000
13    papel higienico   4.559545
14       oleo de soja   4.640000
23              vinho  30.744615
24           macarrao   3.611538
27            shampoo  11.070000
28           presunto  10.862857
30            cerveja   3.460000
34       papel toalha   3.600000
36     pasta de dente   3.520000
40       pao de forma   7.360000
45        sabao em po   9.410000
48          amaciante   6.727949
51       desinfetante   5.840000
53       refrigerante   6.170000
64              arroz   6.950000
65   farinha de trigo   3.659231
67  biscoito recheado   3.640000
75                sal   2.637468
77    suco de laranja   6.738636
80     leite integral   4.710000
90         detergente   3.639231

In [88]:
df['cliente'] = df['cliente'].str.lower()

In [89]:
df['vendedir'] = df['vendedor'].str.lower()

In [93]:
df.to_csv("dados_limpos.csv", index=False)